# Generated by Django 5.0 on 2024-02-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='MyBook',
        ),
    ]
