# Generated by Django 5.0 on 2024-02-02 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book-images/')),
                ('isbn', models.CharField(max_length=255)),
                ('book_name', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField()),
                ('returned_date', models.DateField()),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.book')),
            ],
        ),
    ]
