# Generated by Django 3.0.5 on 2023-11-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowedbook_id', models.IntegerField()),
                ('borrowedbook_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=255)),
                ('borrowed_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('fine', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
