# Generated by Django 5.0 on 2024-02-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='is_borrowed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
