# Generated by Django 3.0.5 on 2023-11-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_borrowedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='id',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowedbook_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
