# Generated by Django 3.0.5 on 2023-11-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20231122_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowedbook_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
