# Generated by Django 5.0 on 2024-01-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
